# Build configuration for code generation
targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          - lib/data/models/*.dart
      json_serializable:
        enabled: true
        generate_for:
          - lib/data/models/*.dart
      riverpod_generator:
        enabled: true
        generate_for:
          - lib/**/*_provider.dart
          - lib/**/providers/*.dart
          - lib/data/repositories/*.dart
